/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pages;

import components.PaymentView;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import main.MainFrame;
import services.TransactionServices;


public class CheckPaymentPage extends javax.swing.JPanel {
    
    private TransactionServices transactionServices = new TransactionServices();
    private PaymentView pv = new PaymentView();
    NumberFormat nf = NumberFormat.getInstance(Locale.of("id", "ID"));
    
    private String qrisDesk =
    "QRIS (Pembayaran Instan)\n" +
    "1. Buka aplikasi pembayaran digital seperti DANA, OVO, GoPay, ShopeePay, atau mobile banking yang mendukung QRIS.\n" +
    "2. Pilih menu Scan QR atau QRIS Payment.\n\n" +
    "3. Arahkan kamera ke kode QR yang muncul pada halaman pembayaran.\n\n" +
    "4. Periksa kembali nama penerima dan nominal pembayaran. Jika nominal belum otomatis, masukkan sesuai tagihan.\n\n" +
    "5. Konfirmasikan pembayaran dan tunggu hingga transaksi dinyatakan berhasil.\n\n" +
    "6. Simpan bukti pembayaran atau screenshot untuk keperluan verifikasi.";

    private String bcaDesk =
    "Transfer Bank BCA\n" +
    "1. Buka BCA Mobile, KlikBCA, atau gunakan ATM BCA.\n\n" +
    "2. Pilih menu Transfer lalu pilih Ke Rekening BCA.\n\n" +
    "3. Masukkan nomor rekening tujuan yang tertera di halaman pembayaran.\n\n" +
    "4. Input jumlah pembayaran sesuai tagihan.\n\n" +
    "5. Periksa apakah nama penerima yang muncul sudah benar.\n\n" +
    "6. Konfirmasi transaksi dan tunggu hingga status pembayaran berhasil.\n\n" +
    "7. Simpan bukti transfer jika diperlukan untuk verifikasi.";

    private String bniDesk =
    "Transfer Bank BNI\n" +
    "1. Buka BNI Mobile Banking, Internet Banking BNI, atau ATM BNI.\n\n" +
    "2. Masuk ke menu Transfer lalu pilih Antar Rekening BNI.\n\n" +
    "3. Masukkan nomor rekening tujuan sesuai instruksi pembayaran.\n\n" +
    "4. Masukkan nominal pembayaran sesuai tagihan.\n\n" +
    "5. Pastikan nama penerima sudah benar sebelum melanjutkan.\n\n" +
    "6. Konfirmasi transaksi hingga muncul notifikasi sukses.\n\n" +
    "7. Simpan bukti pembayaran untuk proses verifikasi.";

    private String briDesk =
    "Transfer Bank BRI\n" +
    "1. Buka BRImo, Internet Banking BRI, atau ATM BRI.\n\n" +
    "2. Pilih menu Transfer lalu pilih Sesama BRI.\n\n" +
    "3. Masukkan rekening tujuan yang tertera pada halaman pembayaran.\n\n" +
    "4. Isi nominal pembayaran sesuai jumlah tagihan.\n\n" +
    "5. Periksa kembali nama penerima sebelum menyelesaikan transaksi.\n\n" +
    "6. Konfirmasikan pembayaran dan tunggu hingga transaksi berhasil.\n\n" +
    "7. Simpan bukti transfer jika diperlukan untuk pengecekan.";
    
    private MainFrame frame;
    
    private String order_id;
    private int total_price;
    
    public CheckPaymentPage(MainFrame frame) {
        this.frame = frame;
        initComponents();
        
        lbVirtualAccount.setVisible(false);
        pictureBox.setVisible(false);
    }
    
    public void loadData(String metode_pembayaran, String order_id, int total_price){
        this.order_id = order_id;
        this.total_price = total_price;
        
        lbTotal_Price.setText("Rp. " + nf.format(total_price));
        
        if(metode_pembayaran.equals("QRIS")){
            lbVirtualAccount.setVisible(false);
            pictureBox.setVisible(true);
            TextArea.setText(qrisDesk);
            pictureBox.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/qr.png")));
            lbPembayaran.setText("Qris");
        } else if(metode_pembayaran.equals("BCA")){
            pictureBox.setVisible(false);
            lbVirtualAccount.setVisible(true);
            TextArea.setText(bcaDesk);
            pictureBox.setImage(null);
            lbPembayaran.setText("Virtual Account");
            lbVirtualAccount.setText("123456788901023");
        } else if (metode_pembayaran.equals("BNI")) {
            pictureBox.setVisible(false);
            lbVirtualAccount.setVisible(true);
            TextArea.setText(bniDesk);
            pictureBox.setImage(null);
            lbPembayaran.setText("Virtual Account");
            lbVirtualAccount.setText("8808001234567890");
        } else if (metode_pembayaran.equals("BRI")) {
            pictureBox.setVisible(false);
            lbVirtualAccount.setVisible(true);
            TextArea.setText(briDesk);
            pictureBox.setImage(null);
            lbPembayaran.setText("Virtual Account");
            lbVirtualAccount.setText("2255512345678901");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbPembayaran = new javax.swing.JLabel();
        pictureBox = new components.PictureBox();
        lbTotal_Price = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lbVirtualAccount = new javax.swing.JLabel();
        lbIntruksiPembayaran = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        ButtonBeli2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lb1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb1.setForeground(new java.awt.Color(0, 101, 248));
        lb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb1.setText("Payment");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(449, 449, 449)
                .addComponent(lb1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb1)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        lbPembayaran.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbPembayaran.setText("Virtual Account");

        pictureBox.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/qr.png"))); // NOI18N

        lbTotal_Price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTotal_Price.setForeground(new java.awt.Color(0, 101, 248));
        lbTotal_Price.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTotal_Price.setText("Rp. 200.000");

        lb2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb2.setText("Total");

        lbVirtualAccount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbVirtualAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbVirtualAccount.setText("Virtual Account");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pictureBox, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbVirtualAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbTotal_Price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE))
                        .addGap(17, 17, 17))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbPembayaran)
                .addGap(26, 26, 26)
                .addComponent(lbVirtualAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pictureBox, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTotal_Price)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        lbIntruksiPembayaran.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbIntruksiPembayaran.setText("Intruksi Pembayaran");

        TextArea.setEditable(false);
        TextArea.setColumns(20);
        TextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextArea.setLineWrap(true);
        TextArea.setRows(5);
        TextArea.setText("Buka aplikasi pembayaran digital seperti DANA, OVO, GoPay, ShopeePay, atau mobile banking yang mendukung QRIS.\n\nPilih menu Scan QR atau QRIS Payment pada aplikasi Anda.\n\nArahkan kamera ke kode QR yang tampil di halaman pembayaran aplikasi kami.\n\nPeriksa kembali nama penerima dan nominal pembayaran. Jika nominal belum otomatis, masukkan jumlah sesuai tagihan.\n\nKonfirmasi transaksi dan tunggu proses pembayaran selesai. Biasanya hanya memerlukan beberapa detik.\n\nSimpan bukti pembayaran atau screenshot untuk keperluan verifikasi apabila dibutuhkan.");
        TextArea.setWrapStyleWord(true);
        TextArea.setBorder(null);
        TextArea.setFocusable(false);
        jScrollPane1.setViewportView(TextArea);

        ButtonBeli2.setBackground(new java.awt.Color(0, 101, 248));
        ButtonBeli2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        ButtonBeli2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBeli2.setText("Cek Status Pembayaran");
        ButtonBeli2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonBeli2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBeli2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButtonBeli2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbIntruksiPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(52, 52, 52))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                                        .addGap(33, 33, 33)))
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(29, 29, 29)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbIntruksiPembayaran)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(ButtonBeli2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBeli2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBeli2ActionPerformed
        int result = transactionServices.updatePaymentService(order_id);
        if(result == 200){
            MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
            main.showSuccessPage(order_id, total_price);
        } else {
            JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this), "Internal Server Error");
        }
    }//GEN-LAST:event_ButtonBeli2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBeli2;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbIntruksiPembayaran;
    private javax.swing.JLabel lbPembayaran;
    private javax.swing.JLabel lbTotal_Price;
    private javax.swing.JLabel lbVirtualAccount;
    private components.PictureBox pictureBox;
    // End of variables declaration//GEN-END:variables
}
