/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.CardLayout;
import javax.swing.JPanel;
import models.ModelAlamat;
import models.ModelUser;
import pages.AdminProductPage;
import pages.AdminTransactionPage;
import pages.CartPage;
import pages.CheckPaymentPage;
import pages.HomePage;
import pages.LoginPage;
import pages.PaymentPage;
import pages.ProductPage;
import pages.RegisterPage;
import pages.RiwayatPage;
import pages.SuccessPage;

/**
 *
 * @author Rafy1
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    private CardLayout cardLayout;   
    private JPanel mainPanel;
    private CartPage cartPage;
    private ProductPage productPage;
    private PaymentPage paymentPage;
    private CheckPaymentPage checkPaymentPage;
    private SuccessPage successPage;
    private HomePage homePage;
    private RiwayatPage riwayatPage;
    private AdminProductPage adminProductPage;
    private AdminTransactionPage adminTransactionPage;
    
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        cardLayout = new CardLayout();
        mainPanel = new JPanel(cardLayout);
        // Tambah halaman        
        mainPanel.add(new RegisterPage(this), "register");
        mainPanel.add(new LoginPage(this), "login");
        
        setContentPane(mainPanel);
        showPage("login");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2000, 1700));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }
    
    public void showHomePage(){
        if (homePage == null) {
            homePage = new HomePage(this);
            mainPanel.add(homePage, "home");
        }
        
        homePage.loadData();
        showPage("home");
    }
    
    public void showCartPage(int userId){
        if (cartPage == null) {
            cartPage = new CartPage(this);
            mainPanel.add(cartPage, "cart");
        }
        
        cartPage.loadData(userId);
        showPage("cart");
    }
    
    public void showProductPage(int id_product) {
        if (productPage == null) {
            productPage = new ProductPage(this);
            mainPanel.add(productPage, "product");
        }

        productPage.loadData(id_product);
        showPage("product");
    }
    
    public void showPaymentPage(int id_user) {
        if (paymentPage == null) {
            paymentPage = new PaymentPage(this);
            mainPanel.add(paymentPage, "payment");
        }

        paymentPage.loadData(id_user);
        showPage("payment");
    }
    
    public void showCheckPaymentPage(String metode_pembayaran, String order_id, int total_price) {
        if (checkPaymentPage == null) {
            checkPaymentPage = new CheckPaymentPage(this);
            mainPanel.add(checkPaymentPage, "checkPayment");
        }

        checkPaymentPage.loadData(metode_pembayaran, order_id, total_price);
        showPage("checkPayment");
    }
    
    public void showSuccessPage(String order_id, int total_price) {
        if (successPage == null) {
            successPage = new SuccessPage(this);
            mainPanel.add(successPage, "success");
        }

        successPage.loadData(order_id, total_price);
        showPage("success");
    }
    
    public void showRiwayatPage(int id_user) {
        if (riwayatPage == null) {
            riwayatPage = new RiwayatPage(this);
            mainPanel.add(riwayatPage, "riwayat");
        }

        riwayatPage.loadData(id_user);
        showPage("riwayat");
    }
    
    public void showAdminProductPage(String role) {
        if(!role.equals("admin")){
            showPage("login");
            return;
        }
        
        if (adminProductPage == null) {
            adminProductPage = new AdminProductPage(this);
            mainPanel.add(adminProductPage, "adminProduct");
        }

        adminProductPage.loadData();
        showPage("adminProduct");
    }
    
    public void showAdminTransactionPage(String role) {
        if(!role.equals("admin")){
            showPage("login");
            return;
        }
        
        if (adminTransactionPage == null) {
            adminTransactionPage = new AdminTransactionPage(this);
            mainPanel.add(adminTransactionPage, "adminTransaction");
        }

        adminTransactionPage.loadData();
        showPage("adminTransaction");
    }
    
    public void showPage(String name) {
        cardLayout.show(mainPanel, name);
    }
    
    public void logout() {
        ModelUser user = new ModelUser();
        ModelAlamat ma = new ModelAlamat();
        
        user.setId(-1);
        user.setFullname(null);
        user.setEmail(null);
        user.setRole(null);
        
        ma.setId(-1);
        ma.setAlamat(null);
        ma.setKode_pos(null);
        ma.setNo_telp(null);
        
        showPage("login");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
