/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

import java.text.NumberFormat;
import java.util.Locale;
import models.ModelTransaction;

/**
 *
 * @author Rafy1
 */
public class CardNameList extends javax.swing.JPanel {

    private ModelTransaction data;
    
    NumberFormat nf = NumberFormat.getInstance(Locale.of("id", "ID"));
    
    public void setData(ModelTransaction data) {
        this.data = data;
        lbNameProduct.setText(data.getNamaProduct());
        lbTotalPrice.setText("Rp. " + nf.format(data.getTotal_harga()));
    }
    
    public CardNameList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNameProduct = new javax.swing.JLabel();
        lbTotalPrice = new javax.swing.JLabel();

        lbNameProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNameProduct.setText("Name Product");

        lbTotalPrice.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbTotalPrice.setText("Rp. 200.000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 80, Short.MAX_VALUE)
                .addGap(78, 78, 78)
                .addComponent(lbTotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNameProduct))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CartProductContainerName;
    private javax.swing.JLabel lbCardProductName;
    private javax.swing.JLabel lbCardProductPrice;
    private javax.swing.JLabel lbNameProduct;
    private javax.swing.JLabel lbTotalPrice;
    // End of variables declaration//GEN-END:variables
}
