/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

import java.awt.Dimension;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.Box;
import javax.swing.SwingUtilities;
import main.MainFrame;
import models.ModelPayment;
import models.ModelTransaction;
import services.TransactionServices;

/**
 *
 * @author Rafy1
 */
public class ContainerBelumBayar extends javax.swing.JPanel {

    private ModelPayment data;
    private TransactionServices transactionServices = new TransactionServices();
    
    NumberFormat nf = NumberFormat.getInstance(Locale.of("id", "ID"));
    
    private String order_id;
    private String metode_pembayaran;
    private int total_price;
    
    public ContainerBelumBayar() {
        initComponents();
    }
    
    public void setData(ModelPayment data, int id_user) {
        this.data = data;
        lbTotalBelumBayar.setText("Rp. " + nf.format(data.getTotal_price()));
        
        order_id = data.getOrder_id();
        total_price = data.getTotal_price();
        metode_pembayaran = data.getMetode_pembayaran();
        
        ArrayList<ModelTransaction> product = transactionServices.getProductPayment(id_user, data.getOrder_id());
        
        containerBelumBayar.removeAll();
        
        for(ModelTransaction item : product){
            CardBelumBayar c = new CardBelumBayar();
            c.setData(item);
            containerBelumBayar.add(c);
            containerBelumBayar.add(Box.createRigidArea(new Dimension(0, 10)));
        }
        
        containerBelumBayar.revalidate();
        containerBelumBayar.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbTotalBelumBayar = new javax.swing.JLabel();
        ButtonBuy = new javax.swing.JButton();
        containerBelumBayar = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 101, 248));
        jLabel1.setText("Belum Bayar");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Total Pembayaran");

        lbTotalBelumBayar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTotalBelumBayar.setForeground(new java.awt.Color(0, 101, 248));
        lbTotalBelumBayar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTotalBelumBayar.setText("Rp. 200.000.000");

        ButtonBuy.setBackground(new java.awt.Color(0, 101, 248));
        ButtonBuy.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ButtonBuy.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBuy.setText("Bayar Sekarang");
        ButtonBuy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuyActionPerformed(evt);
            }
        });

        containerBelumBayar.setBackground(new java.awt.Color(255, 255, 255));
        containerBelumBayar.setLayout(new javax.swing.BoxLayout(containerBelumBayar, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(592, 592, 592)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonBuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTotalBelumBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(798, 798, 798))
                    .addComponent(containerBelumBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(containerBelumBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTotalBelumBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuyActionPerformed
        MainFrame main = (MainFrame) (SwingUtilities.windowForComponent(this));
        main.showCheckPaymentPage(metode_pembayaran, order_id, total_price);
    }//GEN-LAST:event_ButtonBuyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuy;
    private javax.swing.JPanel containerBelumBayar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbTotalBelumBayar;
    // End of variables declaration//GEN-END:variables
}
