/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import main.MainFrame;
import models.ModelAlamat;
import models.ModelTransaction;
import models.ModelUser;
import services.TransactionServices;
import services.UserServices;

/**
 *
 * @author Rafy1
 */
public class PaymentView extends javax.swing.JPanel {

    private int id_user;
    private int total;
    private String metode_pembayaran = "";
    private String orderId;
    
    private TransactionServices transactionServices = new TransactionServices();
    private UserServices userServices = new UserServices();
    NumberFormat nf = NumberFormat.getInstance(Locale.of("id", "ID"));
    private ModelUser user = new ModelUser();
    private ModelAlamat ma = new ModelAlamat();
    
    public PaymentView() {
        initComponents();
    }
    
    public String getOrderId() {
        return orderId;
    }
    
    public void showPayment(int id_user){
        this.id_user = id_user;
        
        userServices.getAlamatUser(id_user);
        
        ArrayList<ModelTransaction> products = transactionServices.getTransaction(id_user);
        
        total = 0;
        
        containerProduct.removeAll();
        
        for (ModelTransaction item : products) {
            PaymentList p = new PaymentList(); 
            p.setData(item);
            containerProduct.add(p);
            total += item.getTotal_harga();
        }
        
        lbTotalSemua.setText("Rp. " + nf.format(total));
        lbTotalSemua2.setText("Rp. " + nf.format(total));
        lbNama.setText(user.getFullname());
        lbAlamat.setText(ma.getAlamat() + ", " + ma.getKode_pos());
        
        containerProduct.revalidate();
        containerProduct.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonBack = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbNama = new javax.swing.JLabel();
        ButtonUbahAlamat = new javax.swing.JLabel();
        lbAlamat = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lb = new javax.swing.JLabel();
        containerProduct = new javax.swing.JPanel();
        lbProduct1 = new javax.swing.JLabel();
        lbTotalSemua = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        qris = new javax.swing.JRadioButton();
        pictureBox2 = new components.PictureBox();
        jPanel9 = new javax.swing.JPanel();
        bca = new javax.swing.JRadioButton();
        pictureBox3 = new components.PictureBox();
        jPanel10 = new javax.swing.JPanel();
        bni = new javax.swing.JRadioButton();
        pictureBox4 = new components.PictureBox();
        jPanel11 = new javax.swing.JPanel();
        bri = new javax.swing.JRadioButton();
        pictureBox5 = new components.PictureBox();
        jPanel12 = new javax.swing.JPanel();
        lbProduct2 = new javax.swing.JLabel();
        lbTotalSemua2 = new javax.swing.JLabel();
        ButtonBuy = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        ButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        ButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(ButtonBack)
                .addContainerGap(944, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(ButtonBack)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 119));

        jPanel3.setBackground(new java.awt.Color(0, 101, 248));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/location.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 101, 248));
        jLabel2.setText("Alamat Pengiriman");

        lbNama.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNama.setText("Nama User");

        ButtonUbahAlamat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonUbahAlamat.setForeground(new java.awt.Color(0, 101, 248));
        ButtonUbahAlamat.setText("Ubah");
        ButtonUbahAlamat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonUbahAlamat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonUbahAlamatMouseClicked(evt);
            }
        });

        lbAlamat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbAlamat.setText("Alamat");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbNama, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lbAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143)
                        .addComponent(ButtonUbahAlamat)
                        .addGap(119, 119, 119))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNama)
                    .addComponent(ButtonUbahAlamat)
                    .addComponent(lbAlamat))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        lb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb.setText("Product dipesan");

        containerProduct.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        lbProduct1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbProduct1.setText("Total");

        lbTotalSemua.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTotalSemua.setForeground(new java.awt.Color(0, 101, 248));
        lbTotalSemua.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTotalSemua.setText("Rp. 20.000.000");

        lb2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb2.setText("Subtotal");

        lb3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb3.setText("Jumlah");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(containerProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(665, 665, 665)
                .addComponent(lbProduct1)
                .addGap(18, 18, 18)
                .addComponent(lbTotalSemua, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lb, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb3)
                .addGap(96, 96, 96)
                .addComponent(lb2)
                .addGap(77, 77, 77))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb)
                    .addComponent(lb2)
                    .addComponent(lb3))
                .addGap(28, 28, 28)
                .addComponent(containerProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProduct1)
                    .addComponent(lbTotalSemua))
                .addGap(32, 32, 32))
        );

        lb1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb1.setText("Metode Pembayaran");

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        qris.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        qris.setText("QRIS");
        qris.setIconTextGap(15);
        qris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qrisActionPerformed(evt);
            }
        });

        pictureBox2.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/qris.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(qris, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(pictureBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(pictureBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(qris)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        bca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bca.setText("BCA");
        bca.setIconTextGap(15);
        bca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcaActionPerformed(evt);
            }
        });

        pictureBox3.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/bca.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(bca, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pictureBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(pictureBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(bca)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        bni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bni.setText("BNI");
        bni.setIconTextGap(15);
        bni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bniActionPerformed(evt);
            }
        });

        pictureBox4.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/bni.png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(bni, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pictureBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(pictureBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(bni)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        bri.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bri.setText("BRI");
        bri.setIconTextGap(15);
        bri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                briActionPerformed(evt);
            }
        });

        pictureBox5.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/bri.png"))); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(bri, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pictureBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addComponent(pictureBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(bri)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lb1)
                .addGap(28, 28, 28)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        lbProduct2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbProduct2.setText("Total");

        lbTotalSemua2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTotalSemua2.setForeground(new java.awt.Color(0, 101, 248));
        lbTotalSemua2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTotalSemua2.setText("Rp. 20.000.000");

        ButtonBuy.setBackground(new java.awt.Color(0, 101, 248));
        ButtonBuy.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ButtonBuy.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBuy.setText("Buat Pesanan");
        ButtonBuy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ButtonBuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(lbProduct2)
                        .addGap(40, 40, 40)
                        .addComponent(lbTotalSemua2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProduct2)
                    .addComponent(lbTotalSemua2))
                .addGap(18, 18, 18)
                .addComponent(ButtonBuy, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonBackMouseClicked
        MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
        main.showCartPage(id_user);
    }//GEN-LAST:event_ButtonBackMouseClicked

    private void qrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qrisActionPerformed
        if(qris.isSelected()){
            metode_pembayaran = qris.getText();
            bca.setSelected(false);
            bni.setSelected(false);
            bri.setSelected(false);
        } else {
            metode_pembayaran = "";
        }
    }//GEN-LAST:event_qrisActionPerformed

    private void bcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcaActionPerformed
        if(bca.isSelected()){
            metode_pembayaran = bca.getText();
            qris.setSelected(false);
            bni.setSelected(false);
            bri.setSelected(false);
        } else {
            metode_pembayaran = "";
        }
    }//GEN-LAST:event_bcaActionPerformed

    private void bniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bniActionPerformed
        if(bni.isSelected()){
            metode_pembayaran = bni.getText();
            bca.setSelected(false);
            qris.setSelected(false);
            bri.setSelected(false);
        } else {
            metode_pembayaran = "";
        }
    }//GEN-LAST:event_bniActionPerformed

    private void briActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_briActionPerformed
        if(bri.isSelected()){
            metode_pembayaran = bri.getText();
            bca.setSelected(false);
            bni.setSelected(false);
            qris.setSelected(false);
        } else {
            metode_pembayaran = "";
        }
    }//GEN-LAST:event_briActionPerformed

    private void ButtonBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuyActionPerformed
        if(metode_pembayaran.length() == 0){
            JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this), "Pilih salah satu metode pembayaran");
        } else {
            orderId = "ORD" + System.currentTimeMillis();
            int result = transactionServices.updateOrderId(orderId, id_user);
            if(result == 200){
                int paymentResult = transactionServices.paymentService(orderId, metode_pembayaran, total);
                if(paymentResult == 200){
                    MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
                    main.showCheckPaymentPage(metode_pembayaran, orderId, total);
                } else {
                    JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this), "Internal Server Error");
                }
            } else {
                JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this), "Internal Server Error");
            }
        }
    }//GEN-LAST:event_ButtonBuyActionPerformed

    private void ButtonUbahAlamatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonUbahAlamatMouseClicked
        JTextField alamat = new JTextField(ma.getAlamat());
        JTextField no_telp = new JTextField(ma.getNo_telp());
        JTextField kode_pos = new JTextField(ma.getKode_pos());

        Object[] alamatUser = {
            "Alamat:", alamat,
            "Nomor Telphone:", no_telp,
            "Kode Pos:", kode_pos,
        };

        int result = JOptionPane.showConfirmDialog(SwingUtilities.getWindowAncestor(this), alamatUser, "Lengkapi Alamat Anda", JOptionPane.OK_CANCEL_OPTION);
        if(result == JOptionPane.OK_OPTION){
            if(alamat.getText().trim().isEmpty() || no_telp.getText().trim().isEmpty() || kode_pos.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this), "Data tidak boleh kosong");
                return;
            }

           int resultUpdateAlamat = userServices.updateAlamatUser(id_user, alamat.getText().trim(), no_telp.getText().trim(), kode_pos.getText().trim());
           if(resultUpdateAlamat == 200){
                int okClick = JOptionPane.showConfirmDialog(SwingUtilities.getWindowAncestor(this),"Alamat berhasil diubah","Informasi",JOptionPane.DEFAULT_OPTION,JOptionPane.INFORMATION_MESSAGE);
                if (okClick == JOptionPane.OK_OPTION) {
                    MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
                    main.showPaymentPage(id_user);
                }
            } else if(resultUpdateAlamat == 404){
                JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this), "Data tidak ditemukan");
            } else {
                JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this), "Internal Server Error");
            }
        }
    }//GEN-LAST:event_ButtonUbahAlamatMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ButtonBack;
    private javax.swing.JButton ButtonBuy;
    private javax.swing.JLabel ButtonUbahAlamat;
    private javax.swing.JRadioButton bca;
    private javax.swing.JRadioButton bni;
    private javax.swing.JRadioButton bri;
    private javax.swing.JPanel containerProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lbAlamat;
    private javax.swing.JLabel lbNama;
    private javax.swing.JLabel lbProduct1;
    private javax.swing.JLabel lbProduct2;
    private javax.swing.JLabel lbTotalSemua;
    private javax.swing.JLabel lbTotalSemua2;
    private components.PictureBox pictureBox2;
    private components.PictureBox pictureBox3;
    private components.PictureBox pictureBox4;
    private components.PictureBox pictureBox5;
    private javax.swing.JRadioButton qris;
    // End of variables declaration//GEN-END:variables
}
