/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

import java.awt.Graphics;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import models.ModelTransaction;
import models.ModelUser;
import services.ProductServices;

/**
 *
 * @author Rafy1
 */
public class ProductCart extends javax.swing.JPanel {
    
    private ModelTransaction data;
    ModelUser user = new ModelUser();
    
    private int id;
    private int jumlah;
    private int stok;
    
    private Runnable onUpdate;
    
    NumberFormat nf = NumberFormat.getInstance(Locale.of("id", "ID"));
    
    public void setOnUpdate(Runnable onUpdate){
        this.onUpdate = onUpdate;
    }
    
    public void setData(ModelTransaction data) {
        this.data = data;
        lbNameProduct.setText(data.getNamaProduct());
        lbPrice.setText("Rp. " + nf.format(data.getTotal_harga()));
        lbJumlah.setText(Integer.toString(data.getTotal_jumlah()));
        pic.setImage(data.getGambar());
        id = data.getIdProduct();
        jumlah = data.getTotal_jumlah();
        stok = data.getStok();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
    }
    
    public ProductCart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pic = new components.PictureBox();
        lbNameProduct = new javax.swing.JLabel();
        lbPrice = new javax.swing.JLabel();
        lbJumlah = new javax.swing.JLabel();
        ButtonPlus = new javax.swing.JButton();
        ButtonMinus = new javax.swing.JButton();

        pic.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/p1.png"))); // NOI18N

        lbNameProduct.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lbNameProduct.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNameProduct.setText("Name Product");

        lbPrice.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lbPrice.setText("Rp. 100.000");

        lbJumlah.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lbJumlah.setText("1");

        ButtonPlus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        ButtonPlus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPlusActionPerformed(evt);
            }
        });

        ButtonMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remove.png"))); // NOI18N
        ButtonMinus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMinusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ButtonMinus)
                        .addGap(16, 16, 16)
                        .addComponent(lbJumlah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonPlus))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPrice)
                            .addComponent(lbNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lbNameProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPrice)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbJumlah)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ButtonPlus, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ButtonMinus, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPlusActionPerformed
        if(jumlah >= 10){
            JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this), "Pembelian barang tidak boleh lebih dari 10 unit!");
            jumlah = 10;
            return;
        } else if(jumlah >= stok){
            JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this), "Stok untuk barang ini hanya tersisa " + stok + " unit saja!");
            return;
        }
        
        ProductServices buy = new ProductServices();
        jumlah++;
        lbJumlah.setText(Integer.toString(jumlah));
        buy.buyProductService(user.getId(), id, 1);
        
        if(onUpdate != null){
            onUpdate.run();
        }
    }//GEN-LAST:event_ButtonPlusActionPerformed

    private void ButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMinusActionPerformed
        ProductServices buy = new ProductServices();
        jumlah--;
        lbJumlah.setText(Integer.toString(jumlah));
        buy.buyProductService(user.getId(), id, -1);
        
        if(onUpdate != null){
            onUpdate.run();
        }
    }//GEN-LAST:event_ButtonMinusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonMinus;
    private javax.swing.JButton ButtonPlus;
    private javax.swing.JLabel lbJumlah;
    private javax.swing.JLabel lbNameProduct;
    private javax.swing.JLabel lbPrice;
    private components.PictureBox pic;
    // End of variables declaration//GEN-END:variables
}
