/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

import java.awt.Graphics;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.SwingUtilities;
import main.MainFrame;
import models.ModelProduct;
import models.ModelUser;

/**
 *
 * @author Rafy1
 */
public class Product extends javax.swing.JPanel {

    private int id;
    
    NumberFormat nf = NumberFormat.getInstance(Locale.of("id", "ID"));
    
    private ModelProduct data;
    ModelUser user = new ModelUser();
    
    public Product() {
        initComponents();
    }
 
    public void setData(ModelProduct data) {
        this.data = data;
        lbNameProduct.setText(data.getNamaProduct());
        lbPrice.setText("Rp. " + nf.format(data.getPrice()));
        pic.setImage(data.getImage());
        id = data.getId();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNameProduct = new javax.swing.JLabel();
        pic = new components.PictureBox();
        lbPrice = new javax.swing.JLabel();
        buttonBuy = new javax.swing.JButton();
        lbJumlah = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 238, 238));

        lbNameProduct.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbNameProduct.setText("Item Name");

        pic.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/p1.png"))); // NOI18N

        lbPrice.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbPrice.setText("Rp. 5.000.000");

        buttonBuy.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        buttonBuy.setForeground(new java.awt.Color(255, 255, 255));
        buttonBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cart.png"))); // NOI18N
        buttonBuy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuyActionPerformed(evt);
            }
        });

        lbJumlah.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbJumlah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNameProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonBuy)
                    .addComponent(lbJumlah))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuyActionPerformed
        MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
        main.showProductPage(id);
    }//GEN-LAST:event_buttonBuyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuy;
    private javax.swing.JLabel lbJumlah;
    private javax.swing.JLabel lbNameProduct;
    private javax.swing.JLabel lbPrice;
    private components.PictureBox pic;
    // End of variables declaration//GEN-END:variables
}
