/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import main.MainFrame;
import models.ModelProduct;
import models.ModelUser;
import services.ProductServices;

/**
 *
 * @author Rafy1
 */
public class ProductView extends javax.swing.JPanel {
    private ProductServices productServices = new ProductServices();
    NumberFormat nf = NumberFormat.getInstance(Locale.of("id", "ID"));
    
    ModelUser user = new ModelUser();
    
    private int jumlah = 1;
    private int id_product;
    private int stok;
    
    public ProductView() {
        initComponents();
        
        TextAreaDeskripsi.setBorder(null);
        lbJumlah.setText(Integer.toString(jumlah));
        buttonBuyMinus.setEnabled(false);
    }
    
    public void getProduct(int id_product){
        this.id_product = id_product;
        ArrayList<ModelProduct> product = productServices.getProductService(id_product);
        
        for(ModelProduct item : product){
            lbNamaProduct.setText(item.getNamaProduct());
            lbNamaProduct1.setText(item.getNamaProduct());
            lbHarga.setText("Rp. " + nf.format(item.getPrice()));
            lbStok.setText(Integer.toString(item.getStok()));
            pic.setImage(item.getImage());
            TextAreaDeskripsi.setText(item.getDeskripsi());
            stok = item.getStok();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonBack = new javax.swing.JLabel();
        lbNamaProduct = new javax.swing.JLabel();
        lbHarga = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbNamaProduct1 = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        lbStok = new javax.swing.JLabel();
        ButtonBuy = new javax.swing.JButton();
        buttonBuyMinus = new javax.swing.JButton();
        buttonBuyPlus = new javax.swing.JButton();
        lbJumlah = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pic = new components.PictureBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaDeskripsi = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        ButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        ButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(ButtonBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(ButtonBack)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        lbNamaProduct.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lbNamaProduct.setText("Nama Product");

        lbHarga.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lbHarga.setText("Rp. 20.000.000");

        lbNamaProduct1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lbNamaProduct1.setText("Nama Product");

        lb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb.setText("Stok");

        lbStok.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbStok.setText("100");

        ButtonBuy.setBackground(new java.awt.Color(0, 101, 248));
        ButtonBuy.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ButtonBuy.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cartWhite.png"))); // NOI18N
        ButtonBuy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuyActionPerformed(evt);
            }
        });

        buttonBuyMinus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        buttonBuyMinus.setForeground(new java.awt.Color(255, 255, 255));
        buttonBuyMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remove.png"))); // NOI18N
        buttonBuyMinus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonBuyMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuyMinusActionPerformed(evt);
            }
        });

        buttonBuyPlus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        buttonBuyPlus.setForeground(new java.awt.Color(255, 255, 255));
        buttonBuyPlus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        buttonBuyPlus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonBuyPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuyPlusActionPerformed(evt);
            }
        });

        lbJumlah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbJumlah.setText("1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonBuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buttonBuyMinus)
                        .addGap(16, 16, 16)
                        .addComponent(lbJumlah)
                        .addGap(18, 18, 18)
                        .addComponent(buttonBuyPlus))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbNamaProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lb)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbStok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbNamaProduct1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb)
                    .addComponent(lbStok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonBuyMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonBuyPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbJumlah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(ButtonBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pic.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/p1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Deskripsi");

        TextAreaDeskripsi.setEditable(false);
        TextAreaDeskripsi.setBackground(new java.awt.Color(255, 255, 255));
        TextAreaDeskripsi.setColumns(20);
        TextAreaDeskripsi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextAreaDeskripsi.setLineWrap(true);
        TextAreaDeskripsi.setRows(5);
        TextAreaDeskripsi.setText("\"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?\"");
        TextAreaDeskripsi.setToolTipText("");
        TextAreaDeskripsi.setWrapStyleWord(true);
        TextAreaDeskripsi.setAutoscrolls(false);
        TextAreaDeskripsi.setBorder(null);
        TextAreaDeskripsi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TextAreaDeskripsi.setFocusable(false);
        TextAreaDeskripsi.setMargin(new java.awt.Insets(2, 5, 2, 6));
        jScrollPane1.setViewportView(TextAreaDeskripsi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(lbNamaProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNamaProduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbHarga)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonBackMouseClicked
        jumlah = 1;
        lbJumlah.setText(Integer.toString(jumlah));
        buttonBuyMinus.setEnabled(false);
        MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
        main.showPage("home");
    }//GEN-LAST:event_ButtonBackMouseClicked

    private void ButtonBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuyActionPerformed
        int result = productServices.buyProductService(user.getId(), id_product, jumlah);
        if(result == 200 || result == 201){
            JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this), "Barang berhasil ditambah ke dalam keranjang");
        } else if(result == 505){
            JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this), "Pembelian barang tidak boleh lebih dari 10 unit! Tolong cek keranjang anda");
        } else if (result == 404){
            JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this), "Barang tidak ditemukan!");
        } else if (result == 500){
            JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this), "Internal Server Error!");
        } else if (result == 506){
            JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this), "Stok untuk barang ini hanya tersisa " + stok + " unit saja! Tolong periksa keranjang anda");
        }
    }//GEN-LAST:event_ButtonBuyActionPerformed

    private void buttonBuyPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuyPlusActionPerformed
        if(jumlah >= 10){
            JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this), "Kamu hanya bisa membeli maksimal 10 unit");
            return;
        } else if(jumlah >= stok){
            JOptionPane.showMessageDialog(SwingUtilities.getWindowAncestor(this), "Stok untuk barang ini hanya tersisa " + stok + " unit saja!");
            return;
        }
        
        jumlah++;
        lbJumlah.setText(Integer.toString(jumlah));
        buttonBuyMinus.setEnabled(true);
    }//GEN-LAST:event_buttonBuyPlusActionPerformed

    private void buttonBuyMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuyMinusActionPerformed
        if(jumlah - 1 == 1){
            buttonBuyMinus.setEnabled(false);
        }
        jumlah--;
        lbJumlah.setText(Integer.toString(jumlah));
    }//GEN-LAST:event_buttonBuyMinusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ButtonBack;
    private javax.swing.JButton ButtonBuy;
    private javax.swing.JTextArea TextAreaDeskripsi;
    private javax.swing.JButton buttonBuyMinus;
    private javax.swing.JButton buttonBuyPlus;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lbHarga;
    private javax.swing.JLabel lbJumlah;
    private javax.swing.JLabel lbNamaProduct;
    private javax.swing.JLabel lbNamaProduct1;
    private javax.swing.JLabel lbStok;
    private components.PictureBox pic;
    // End of variables declaration//GEN-END:variables
}
