/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

import java.awt.Dimension;
import java.util.ArrayList;

import javax.swing.Box;
import javax.swing.SwingUtilities;
import main.MainFrame;
import models.ModelPayment;
import services.TransactionServices;

/**
 *
 * @author Rafy1
 */
public class RiwayatView extends javax.swing.JPanel {

    private TransactionServices transactionServices = new TransactionServices();
    
    public RiwayatView() {
        initComponents();
        
        lbBelumAdaRiwayat.setVisible(false);
        blockDikirim.setVisible(false);
        blockBelumBayar.setVisible(false);
    }
    
    public void showAllPayment(int id_user){
        ArrayList<ModelPayment> list = transactionServices.getAllPayment(id_user);
        
        blockDikirim.setVisible(false);
        blockBelumBayar.setVisible(false);
        
        blockDikirim.removeAll();
        blockBelumBayar.removeAll();
        
        for(ModelPayment item : list){
            if(item.getPayment_status().equals("pending")){
                blockBelumBayar.setVisible(true);
                ContainerBelumBayar cb = new ContainerBelumBayar();
                cb.setData(item, id_user);
                blockBelumBayar.add(cb);
                blockBelumBayar.add(Box.createRigidArea(new Dimension(0, 10)));
            } else if(item.getPayment_status().equals("success")){
                blockDikirim.setVisible(true);
                ContainerDikirim cb = new ContainerDikirim();
                cb.setData(item, id_user);
                blockDikirim.add(cb);
                blockDikirim.add(Box.createRigidArea(new Dimension(0, 10)));
            }
        }
        
        blockBelumBayar.revalidate();
        blockBelumBayar.repaint();
        blockDikirim.revalidate();
        blockDikirim.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbBelumAdaRiwayat = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ButtonBack = new javax.swing.JLabel();
        blockBelumBayar = new javax.swing.JPanel();
        blockDikirim = new javax.swing.JPanel();

        lbBelumAdaRiwayat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbBelumAdaRiwayat.setForeground(new java.awt.Color(153, 153, 153));
        lbBelumAdaRiwayat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBelumAdaRiwayat.setText("Belum Ada Riwayat Belanja!");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        ButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(ButtonBack)
                .addContainerGap(944, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(ButtonBack)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        blockBelumBayar.setPreferredSize(new java.awt.Dimension(0, 0));
        blockBelumBayar.setLayout(new javax.swing.BoxLayout(blockBelumBayar, javax.swing.BoxLayout.Y_AXIS));

        blockDikirim.setPreferredSize(new java.awt.Dimension(0, 0));
        blockDikirim.setLayout(new javax.swing.BoxLayout(blockDikirim, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blockBelumBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blockDikirim, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(blockBelumBayar, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(blockDikirim, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonBackMouseClicked
        MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
        main.showHomePage();
    }//GEN-LAST:event_ButtonBackMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ButtonBack;
    private javax.swing.JPanel blockBelumBayar;
    private javax.swing.JPanel blockDikirim;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBelumAdaRiwayat;
    // End of variables declaration//GEN-END:variables
}
